### ISSUE TITLE
How to get the prompt back after a reload?

### ISSUE THREAD

**Issue by skilbjo** [pyronicide/lein-autoreload#1]
Hi- after a save, this happens:

![image](https://cloud.githubusercontent.com/assets/1145927/18413636/4e3d376c-7762-11e6-90fb-586bd1079ea6.png)

But it'd be great to get the prompt back, ie:

![image](https://cloud.githubusercontent.com/assets/1145927/18413640/6b7a869a-7762-11e6-82e9-598fe9753fcd.png)

Happy to do a PR, but could you point me in the direction of how to do this?

**Comment by grampelberg** [comment]
That message should be coming from `clojure.tools.namespace.repl/refresh`. Take a look there and see what the options are. The message specifically is getting produced by a separate thread, so it doesn't affect your terminal at all.

**Comment by skilbjo** [comment]
pls see: https://github.com/pyronicide/lein-autoreload/pull/2

**Comment by skilbjo** [comment]
Also, I see that `clojure.tools.namespace.repl/refresh` has an `:after` (http://clojure.github.io/tools.namespace/#clojure.tools.namespace.repl), so also this is a possibility (I hope I've got the syntax right ???):

```
(clojure.tools.namespace.repl/refresh :after 'clojure.main/repl-prompt)
```

> refresh
> 
> >  function
> >  Usage: (refresh & options)
> >  Options are key-value pairs. Valid options are:
> > 
> > > ```
> > > :after   Namespace-qualified symbol naming a zero-argument
> > >          function to be invoked after a successful refresh. This
> > >          symbol will be resolved *after* all namespaces have
> > >          been reloaded.
> > > ```
